name: Release (Web)

on:
  push:
    branches:
      - debug

permissions:
  contents: read
  packages: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - name: Install Dependencies
        run: yarn
      - name: Create .npmrc to set up the npm auth token
        run: |
          cat << EOF > "$HOME/.npmrc"
            //npm.pkg.github.com/:_authToken=${TOKEN_FOR_PRIVATE_NPM_REPO_ON_GITHUB}
          EOF
        env:
          TOKEN_FOR_PRIVATE_NPM_REPO_ON_GITHUB: ${{ secrets.GITHUB_TOKEN }}
      - name: publish directly
        run: yarn publish
      - name: Create a release pull request or (if this is the release PR) publish a release
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
